stages:
- stage: Compile
  jobs:
  - job: Compile
    container: <Probably a gradle container here>
    steps:
    - script: chmod +x gradlew && ./gradlew build jacocoTestReport
- stage: SonarQube
  jobs:
  - job: Sonarscan
    steps:
    - script: |
        echo "Sonarqube Integration"
- stage: DockerBuildPush
  jobs:
  - job: DockerBuildPush
    steps:
    - template: docker-template.yml
      parameters:
        containerRegistry: 'alex-docker' #service connection name
        repository: 'alexanderjervis/sample-spring-boot' #dockerhub repository name
        dockerfile: '**/Dockerfile' #docker file path
        tags: '$(Build.BuildId)' #docker image tag