stages:
- stage: Compile
  jobs:
  - job: Compile
    container: <Probably a gradle container here>
    steps:
    - script: chmod +x gradlew && ./gradlew build jacocoTestReport
- stage: SonarQube
  jobs:
  - job: Sonarscan
    steps:
    - template: sonar-template.yml
      parameters:
        sonarQube: 'alex-sonar' #service connection name
        projectKey: 'alexanderjervis_sample-spring-boot' #sonar project key
        projectName: 'sample-spring-boot' #sonar project name
- stage: DockerBuildPush
  jobs:
  - job: DockerBuildPush
    steps:
    - template: docker-template.yml
      parameters:
        containerRegistry: 'alex-docker' #service connection name
        repository: 'alexanderjervis/sample-spring-boot' #dockerhub repository name
        dockerfile: '**/Dockerfile' #docker file path
        imageTag: ${{ variables['Build.BuildId'] }} #docker image tag